### PR TITLE
fix: fixes incomplete type for player api function

### LINKED ISSUE #22: getCurrentlyPlayingTrack returns string if nothing is currently playing.
```javascript
let track = await this.spotify.client.player.getCurrentlyPlayingTrack();
console.log(typeof track)
// outputs: string
```

```javascript
if (track === '') {
      console.log('nothing playing currently');

      return;
}
```

Editor gives the following warning:
```shell
This condition will always return 'false' since the types 'CurrentlyPlaying' and 'string' have no overlap.ts(2367)
```

Code works at runtime because the function is returning a string when nothing is playing. I think it should return undefined, or an error, or a status code, to indicate that nothing is playing, and it should indicate that return type in the signature so that typescript doesn't freak out.

### PR DESCRIPTION
**Pull request by patrick-motard**
`getCurrentlyPlayingTrack` returns an empty string if no song is currently
playing. The type response of that function is incorrect, leading to
complile errors. This PR fixes the issue by correcting the type
response.

Fixes #22

### CODE REVIEW

File: src/apis/PlayerApi.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ export class PlayerApi {
    */
   getCurrentlyPlayingTrack(
     options?: GetCurrentlyPlayingTrackOptions,
-  ): Promise<CurrentlyPlaying> {
+  ): Promise<CurrentlyPlaying | String> {
```
Comment (adamgrieger) [inline src/apis/PlayerApi.ts:51]: The string type should be `string` instead of `String`. The [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/basic-types.html#about-number-string-boolean-symbol-and-object) has a note about this.

**Review by adamgrieger — CHANGES_REQUESTED** [review]
I need to create a contribution guide of some sort, but can you remove the `package-lock.json` file? I used `yarn` while developing this, so there's already a `yarn`-specific lock file. I don't know if people generally commit two different types of lock files.

File: src/apis/PlayerApi.ts (hunk 1 above)
Comment (patrick-motard) [reply src/apis/PlayerApi.ts]: Oops! Fixed in https://github.com/adamgrieger/spotify-web-api-ts/pull/23/commits/59c13e4e4044e64d1ebfd72c9dbcb805f8b195b7

**Comment by patrick-motard** [comment]
> I need to create a contribution guide of some sort, but can you remove the `package-lock.json` file? I used `yarn` while developing this, so there's already a `yarn`-specific lock file. I don't know if people generally commit two different types of lock files.

I've removed the `package-lock.json` in https://github.com/adamgrieger/spotify-web-api-ts/pull/23/commits/59c13e4e4044e64d1ebfd72c9dbcb805f8b195b7. I've also added it to `.gitignore` so that npm users don't include it in future PRs. 🥳

**Review by adamgrieger — APPROVED** [review]

**Comment by adamgrieger** [comment]
Thanks, @patrick-motard!
